### ISSUE TITLE
Getting Started/Gradient : Returning to work redirects to broken link

### ISSUE THREAD

**Issue by sachinchaturvedi93** [fastai/course20#10]
#### [For Getting Started/Gradient](https://course.fast.ai/start_gradient.html)

[Returning to work](https://course.fast.ai/update_gradient.html) redirects to a broken link. Are we going to add a new page here for returning to work or should we redirect it to https://course19.fast.ai/start_gradient.html

**Comment by jph00** [comment]
I'll just remove it.
