### ISSUE TITLE
search_images_ddg: 'str' object has no attribute 'decode' in Python 3 

### ISSUE THREAD

**Issue by ragatti** [fastai/course20#45]
Hi, the next line of the search_images_ddg function gives an error in python 3,  because the 'str' is already decoded.
https://github.com/fastai/course20/blob/3199e109dc409c61a6f85d12d682a2fed2b65610/fastbook/__init__.py#L57

An exception could be added with Try.

**Comment by jph00** [comment]
Many thanks. Would you like to do a PR that removes the `decode`? It's not needed since `urlread` does it now.
