### ISSUE TITLE
gradient how to is no more current

### ISSUE THREAD

**Issue by marcblanchet** [fastai/course20#63]
https://course.fast.ai/start_gradient describes the process to setup a paper space gradient instance. However, most likely between the time the instructions were written and now, the instructions are now different. Moreover, it looks like the free access to the terminal is gone, requires the "pro" package at 8$/month. Might want to update the instructions.

**Comment by lamroger** [comment]
Hi @marcblanchet - I'm an engineer at Paperspace and sorry that the docs aren't up to date. My colleague opened a PR a few days ago on updated instructions here if you want to take a look: https://github.com/fastai/course20/pull/64

We still do have a free tier and this should help you get started! https://docs.paperspace.com/gradient/get-started/tutorials-list/gradient-notebooks-tutorial
