### ISSUE TITLE
Instructions in CONTRIBUTING.md state to run nbdev_install_git_hooks as a first step, but it is not found

### ISSUE THREAD

**Issue by jhadjar** [fastai/course20#71]
The instructions in `CONTRIBUDING.md` state:

>Before anything else, please install the git hooks that run automatic scripts during each commit and merge to strip the notebooks of suerpfluous metadata (and avoid merge conflicts). After cloning the repository, run the following command inside it:

The command being `nbdev_install_git_hooks`. It is the only instance of this string in the repository and I cannot find any script or file with that name. I also have found no issue mentioning this. Am I reading the instructions incorrectly?

**Comment by jph00** [comment]
Apologies - you need to install `nbdev` to have that command.
