### ISSUE TITLE
Gradient instructions don't update the course materials

### ISSUE THREAD

**Issue by strickvl** [fastai/course20#8]
I went through the instructions for using [Paperspace Gradient](https://course.fast.ai/start_gradient.html) and set up notebooks etc as required.

Currently the instructions have you update the fastbook code with a `git pull` command in the terminal.

This fails to update the `course-v4` files which are in a separate folder. This is important because if you navigate into the `course-v4` folder (to get the slimmed-down notebooks which are used in the course videos) currently, all the code given to you automatically by paperspace on initialisation of your machine make reference to `fastai2` instead of `fastai`.

So the documentation should probably be changed from:

> Once you click on ‘Terminal’ a new window should open with a terminal. Type:
> 
> `pip install fastai fastcore --upgrade`
> then
> 
> `cd fastbook`
> `git pull`
> 
> Now you should close the terminal window.

to this:

> Once you click on ‘Terminal’ a new window should open with a terminal. Type:
> 
> `pip install fastai fastcore --upgrade`
> then
> 
> `cd fastbook`
> `git pull`
> `cd ../course-v4`
> `git pull`
> Now you should close the terminal window.

**Comment by jph00** [comment]
I'm going to update things to use the `clean` folder of `fastbook` instead. Thanks for filing this issue.
